function Hd = bandpass200k
%BANDPASS200K 返回离散时间滤波器对象。

% MATLAB Code
% Generated by MATLAB(R) 9.10 and DSP System Toolbox 9.12.
% Generated on: 04-Jul-2022 17:13:31

% Equiripple Bandpass filter designed using the FIRPM function.

% All frequency values are in kHz.
Fs = 10000;  % Sampling Frequency

Fstop1 = 170;             % First Stopband Frequency
Fpass1 = 180;             % First Passband Frequency
Fpass2 = 220;             % Second Passband Frequency
Fstop2 = 230;             % Second Stopband Frequency
Dstop1 = 0.1;             % First Stopband Attenuation
Dpass  = 0.057501127785;  % Passband Ripple
Dstop2 = 0.1;             % Second Stopband Attenuation
dens   = 20;              % Density Factor

% Calculate the order from the parameters using FIRPMORD.
[N, Fo, Ao, W] = firpmord([Fstop1 Fpass1 Fpass2 Fstop2]/(Fs/2), [0 1 ...
                          0], [Dstop1 Dpass Dstop2]);

% Calculate the coefficients using the FIRPM function.
b  = firpm(N, Fo, Ao, W, {dens});
Hd = dfilt.dffir(b);

% [EOF]
