function Hd = lowpass10k
%LOWPASS10K 返回离散时间滤波器对象。

% MATLAB Code
% Generated by MATLAB(R) 9.10 and DSP System Toolbox 9.12.
% Generated on: 04-Jul-2022 23:06:05

% Chebyshev Type I Lowpass filter designed using FDESIGN.LOWPASS.

% All frequency values are in kHz.
Fs = 10000;  % Sampling Frequency

Fpass = 10;          % Passband Frequency
Fstop = 15;          % Stopband Frequency
Apass = 1;           % Passband Ripple (dB)
Astop = 20;          % Stopband Attenuation (dB)
match = 'passband';  % Band to match exactly

% Construct an FDESIGN object and call its CHEBY1 method.
h  = fdesign.lowpass(Fpass, Fstop, Apass, Astop, Fs);
Hd = design(h, 'cheby1', 'MatchExactly', match);

% [EOF]
